<?php
 $fields = $this->getRequest()->getParams();
 $user_model = Mage::getModel("user/user");
 $search_user_table = $user_model->searchUser($fields);
 $address_model = Mage::getModel("user/address");
 $address_user_table = $address_model->addressUser($fields);
  ?><button class="button" id="goback_button" ><span id="button_span" ><span id="button_span" ><a href='<?php echo $this->getUrl("user/index/index"); ?>'>GO BACK</a></span ></span></button><?php
?>
<table class="data-table table-hover" id="table_data" border="">
  <colgroup><col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
  </colgroup>
  <thead>
   <tr class="first last" >  
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('USER ID') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('FIRST NAME') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('LAST NAME') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('EMAIL') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('DOB') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('CITY') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('PINCODE') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('CONTACT') ?></span> </th>
  </tr>
  </thead>
  <tbody>
  <?php
  if(empty($search_user_table))
  {
   
  }
  else
  {
   foreach($search_user_table as $row)
    {
   	 $user_id = $row['user_id'];
   	 $user_model = $this->getUserCollection(); 
   	 foreach($user_model as $data_user)
      {
       $user_table_id = $data_user->getUserId();
       if($user_table_id == $user_id)
        {
        	?>
          <tr>
               <td class="a-center" ><?php echo $data_user->getUserId()?> </td>
               <td class="a-center" ><?php echo $data_user->getFirstname()?> </td>
               <td class="a-center" ><?php echo $data_user->getLastname()?> </td>
               <td class="a-center" ><?php echo $data_user->getEmail()?> </td>
               <td class="a-center" ><?php echo $data_user->getDob()?> </td>
               <?php
               $address_model = $this->getAddressCollection();
               foreach($address_model as $data_address)
                {
                 $address_table_id = $data_address->getUserid();
                 if($address_table_id == $user_id)
                  {
                  ?>
                   <td class="a-center" ><?php echo $data_address->getCity()?> </td>
                   <td class="a-center" ><?php echo $data_address->getPincode()?> </td>
                   <td class="a-center" ><?php echo $data_address->getContacts()?> </td>
                  <?php
                  }
                }
               ?>
        </tr>
        <?php
       }
     }
     die();
    }
  }
  if(empty($search_user_table))
  {
   
  }
  else
  {
   foreach($address_user_table as $row)
   {
   	$user_id = $row['userid'];
   	$address_model = $this->getAddressCollection(); 
   	foreach($address_model as $address_user)
     {
      $address_table_id = $address_user->getUserid();
      if($address_table_id == $user_id)
       {
       	?>
        <tr>
               <?php
                $user_model = $this->getUserCollection();
                foreach($user_model as $data_user)
                 {
                  $user_table_id = $data_user->getUserId();
                  if($user_table_id == $user_id)
                   {
                   ?>
                   <td class="a-center" ><?php echo $data_user->getUserId()?> </td>
                   <td class="a-center" ><?php echo $data_user->getFirstname()?> </td>
                   <td class="a-center" ><?php echo $data_user->getLastname()?> </td>
                   <td class="a-center" ><?php echo $data_user->getEmail()?> </td>
                   <td class="a-center" ><?php echo $data_user->getDob()?> </td>
                   <?php
                  }
                 }
               ?>
              <td class="a-center" ><?php echo $address_user->getCity()?> </td>
              <td class="a-center" ><?php echo $address_user->getPincode()?> </td>
              <td class="a-center" ><?php echo $address_user->getContacts()?> </td>
        <?php
       }
     }
   }
  }
  ?>
  </tr>
 </tbody>
</table>
<br />
<br />
