
<form action="<?php echo $this->getUrl('user/index/save'); ?>" method="post" id="form-validate">
  <div class="fieldset" id="fieldset_table" >
    <h2 class="legend"><?php echo $this->__('Enter Your Details') ?></h2>
      <ul class="form-list">
        <li class="fields">
          <div class="customer-name-firstname">
            <div class="field name-firstname">
              <label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name :') ?></label>
                <div class="input-box">
                  <input type="text" id="firstname" name="firstname" value="" class="input-text required-entry">
                </div>
             </div>
               <div class="field name-lastname">
                <label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name :') ?></label>
                  <div class="input-box">
                    <input type="text" id="lastname" name="lastname" value="" class="input-text required-entry">
                  </div>
               </div>
             </div>
          </li>
            <li>
              <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address :') ?></label>
                <div class="input-box">
                  <input type="text" name="email" id="email" value="" class="input-text validate-email required-entry">
              </div>
           </li>
            <li>
              <label for="dob" class="required"><?php echo $this->__('Dob :') ?></label>
                <div class="input-box">
                  <input type="date" name="dob" id="dob" value="" >
              </div>
           </li>
        </ul>
     </div>
      <div class="fieldset" id="fieldset_table" >
        <h2 class="legend"><?php echo $this->__('Enter Your Contact Information') ?></h2>
          <ul class="form-list">
            <li class="fields">
              <div class="customer-address">
                <div class="field address-city">
                  <label for="city" class="required"><?php echo $this->__('City :') ?></label>
                    <div class="input-box">
                      <input type="text" id="city" name="city" value="" class="input-text ">
                    </div>
                </div>
                  <div class="field address-pincode">
                    <label for="pincode" class="required"><em>*</em><?php echo $this->__('Pincode :') ?></label>
                      <div class="input-box">
                        <input type="text" id="pincode" name="pincode" value="" class="input-text required-entry validate-length maximum-length-6 minimum-length-6 validate-digits">
                     </div>
                  </div>
              </div>
            </li>
              <li>
                <label for="contact" class="required"><em>*</em><?php echo $this->__('Contact :') ?></label>
                  <div class="input-box">
                    <input type="text" name="contacts" id="contacts" value="" class="input-text required-entry validate-length maximum-length-10 minimum-length-10 validate-digits">
                </div>
            </li>
         </ul>
     </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            
      <button type="submit" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
      <button class="button" id="button_goback" ><span id="button_span" ><span id="button_span" ><a href='<?php echo $this->getUrl("user/index/index"); ?>'>GO BACK</a></span ></span></button>
        </div>
</form>

  <script type="text/javascript">
      var dataForm = new VarienForm('form-validate', true);
  </script>
