
<table class="data-table cart-table" id="table_data" border="">
  <colgroup><col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
    <col width="1">
  </colgroup>
  <thead>
   <tr class="first last" >
   
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('USER ID') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('FIRST NAME') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('LAST NAME') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('EMAIL') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('DOB') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('CITY') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('PINCODE') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('CONTACT') ?></span> </th>
    <th rowspan="1" ><span class="nobr"> <?php echo $this->__('Delete') ?></span> </th>
  </tr>
  </thead>
 
 <?php
   $user_model = $this->getUserCollection();
    foreach($user_model as $data)
      {
        $user_table_id = $data->getUserId();
  ?>     <tbody>
          <tr class="first last odd" >
            <td class="a-center" ><?php echo $data->getUserId()?> </td>
            <td class="a-center" ><?php echo $data->getFirstname()?> </td>
            <td class="a-center" ><?php echo $data->getLastname()?> </td>
            <td class="a-center" ><?php echo $data->getEmail()?> </td>
            <td class="a-center" ><?php echo $data->getDob()?> </td>
 <?php
        $address_model = $this->getAddressCollection(); 
          foreach($address_model as $data)
            {
              $address_table_id = $data->getUserid();
                if($user_table_id == $address_table_id)
                  {
  ?>
                    <td  class="a-center" ><?php echo $data->getCity()?> </td>
                    <td  class="a-center" ><?php echo $data->getPincode()?> </td>
                    <td  class="a-center" ><?php echo $data->getContacts()?> </td>
                    <td> <a href='<?php echo $this->getUrl("user/index/delete"); ?>?user_id=<?php echo $data->getUserid() ?>'>Delete</a> </td>
 <?php
                  }
            }
      }
 ?>
               <button class="button" id="button" ><span id="button_span" ><span id="button_span" ><a href='<?php echo $this->getUrl("user/form/printform"); ?>'>ADD MORE DATA</a></span></span></button>
         </tr>
       </tbody>
</table>
