 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

 <table class="data-table table-hover" id="table_data" border="">
<colgroup><col width="1">
    <col width="1">
    <col>
    <col width="1">
    <col width="1">
    <col width="1">
        </colgroup>

  <tr>
   <th>User_Id</th>
   <th>FIRST NAME</th>
   <th>LAST NAME</th>
   <th>EMAIL</th>
   <th>DOB</th>
   <th>CITY</th>
   <th>PINCODE</th>
   <th>CONTACT</th>
   <th>Delete</th>
  </tr>
 <?php
 $user_model = Mage::getModel('user/user')->getCollection();
 
 foreach($user_model as $data)
  {
    $id = $data->getUserId();
    echo '<tr class="first last odd" >';
    echo '<td class="a-center last"  >'.$data->getUserId().'</td>';
    echo '<td  class="a-center last"  >'.$data->getFirstname().'</td>';
    echo '<td class="a-center last"  >'.$data->getLastname().'</td>';
    echo '<td class="a-center last" >'.$data->getEmail().'</td>';
    echo '<td class="a-center last" >'.$data->getDob().'</td>';
    $address_model = Mage::getModel('user/address')->getCollection();
     foreach($address_model as $data)
      {
       $id2 = $data->getUserId();
       if($id == $id2)
       {
       echo '<td  class="a-center last" >'.$data->getCity().'</td>';
       echo '<td class="a-center last" >'.$data->getPincode().'</td>';
       echo '<td class="a-center last" >'.$data->getContact().'</td>';
       ?>
     <td><a href='<?php echo $this->getUrl("user/index/delete"); ?>?id=<?php echo $data->getUserId() ?>'>Delete</a></td>
      <?php

     }
      }
         }
    ?>

    <p>
      <b>WANT TO ADD SOME MORE DATA </b>
      <a href='<?php echo $this->getUrl("user/form/printform"); ?>'>CLICK HERE</a>
    </p>
    
     </tr>

 </table>
 </div>
