<br />
 <p>
  <b>WANT TO ADD SOME MORE DATA </b>
   <a href='<?php echo $this->getUrl("user/form/printform"); ?>'>CLICK HERE</a>
 </p>
 <table class="data-table table-hover" id="table_data" border="">
  <tr>
   <th>User_Id</th>
   <th>FIRST NAME</th>
   <th>LAST NAME</th>
   <th>EMAIL</th>
   <th>DOB</th>
   <th>CITY</th>
   <th>PINCODE</th>
   <th>CONTACT</th>
   <th>Delete</th>
  </tr>
 <?php
  $user_model = Mage::getModel('user/user')->getCollection();
  foreach($user_model as $data)
   {
    $id = $data->getUserId();
  ?>
  <tr class="first last odd">
   <td class="a-center last"> <?php echo $data->getUserId() ?> </td>
   <td class="a-center last"> <?php echo $data->getFirstname() ?> </td>
   <td class="a-center last"> <?php echo $data->getLastname() ?> </td>
   <td class="a-center last"> <?php echo $data->getEmail() ?> </td>
   <td class="a-center last"> <?php echo $data->getDob() ?> </td>
   <?php
    $address_model = Mage::getModel('user/address')->getCollection();
    foreach($address_model as $data)
     {
      $id2 = $data->getUserId();
      if($id == $id2)
       {
        ?>
        <td class="a-center last"> <?php echo $data->getCity(); ?> </td>
        <td class="a-center last"> <?php echo $data->getPincode(); ?> </td>
        <td class="a-center last"> <?php echo $data->getContact(); ?> </td>
        <td><a href='<?php echo $this->getUrl("user/index/delete"); ?>?user_id=<?php echo $data->getUserId() ?>'>Delete</a></td>
        <?php
       }
      }
    }
  ?>
 </tr>
</table>